<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5a68abdb07437',
	'title' => 'Page Fields',
	'fields' => array(
		array(
			'key' => 'field_5a70bcaeae3c9',
			'label' => 'Features',
			'name' => 'features',
			'type' => 'checkbox',
			'instructions' => 'Check any features needed for this page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Smaller H1' => 'Smaller H1',
				'Hero' => 'Hero',
				'Small Footer Text' => 'Small Footer Text',
				'Two Column Layout' => 'Two Column Layout',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5a6b689298aa8',
			'label' => 'Smaller Size Heading',
			'name' => 'smaller_size_heading',
			'type' => 'true_false',
			'instructions' => 'If selected, the page H1 will display at 38px instead of 58px.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a70bcaeae3c9',
						'operator' => '==',
						'value' => 'Smaller H1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5a68ece2dc69d',
			'label' => 'Page Small Text',
			'name' => 'page_small_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a70bcaeae3c9',
						'operator' => '==',
						'value' => 'Small Footer Text',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a6b6944e8a2d',
			'label' => 'Right Column Boxes',
			'name' => 'right_column_boxes',
			'type' => 'repeater',
			'instructions' => 'Right column boxes will create a two column layout. Thumbnails, text, and call to action buttons can be put in these boxes',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a70bcaeae3c9',
						'operator' => '==',
						'value' => 'Two Column Layout',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Box',
			'sub_fields' => array(
				array(
					'key' => 'field_5a6b69d8e8a2e',
					'label' => 'Box Thumbnail',
					'name' => 'box_thumbnail',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5a6b6a00e8a2f',
					'label' => 'Box Heading',
					'name' => 'box_heading',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5a6b6a11e8a30',
					'label' => 'Box text',
					'name' => 'box_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5a6b6a4aea5fb',
					'label' => 'Box CTA link',
					'name' => 'box_cta_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5a6b6a60ea5fc',
					'label' => 'Box CTA Label',
					'name' => 'box_cta_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5a70bbe424bca',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a70bcaeae3c9',
						'operator' => '==',
						'value' => 'Hero',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5a70bc1324bcb',
			'label' => 'Hero overlay text',
			'name' => 'hero_overlay_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a70bcaeae3c9',
						'operator' => '==',
						'value' => 'Hero',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
